### ISSUE TITLE
Copy labels from an issue to a linked pull request

### ISSUE THREAD

**Issue by piotrczyz** [dessant/label-actions#13]
Did you consider to sync labels between issues and linked pull requests? Do you see it as an advantage? Is it doable?

As a developer 
I would appreciate to have possibility to automatically copy particular labels from an issue to a pull request 
So that I don't need to manually copy them once a pull request is created.

The big picture is that we're using HayStack to measure our KPIs and they have an approach that bases on pull requests.

**Comment by dessant** [comment]
You may be able to do it from the pull request side, but the API does not directly expose linked issues, and there does not seem to be a one-to-one association between an issue and a pull request on GitHub, so you'd have no way of knowing from which issue to copy labels, unless you have a specific convention on how you mention the target issue in a comment, or you always link only to a single issue. I think your use case is best served by a custom GitHub action.

https://github.community/t/get-all-issues-linked-to-a-pull-request/14653/8

**Comment by dessant** [comment]
Let me know if your company wants to outsource the work, my email is in my profile.
