### ISSUE TITLE
Close as not planned

### ISSUE THREAD

**Issue by mfazekas** [dessant/label-actions#22]
It would be nice to support closing issues as not planned vs completed. It might be even the default.

![image](https://user-images.githubusercontent.com/52435/206966896-384391da-f308-4fc5-9042-6a63c25a230e.png)

![image](https://user-images.githubusercontent.com/52435/206967210-52d1d447-c82b-4e1f-b5ec-4c25cba670d5.png)

**Comment by dessant** [comment]
This feature will be added in the next release, setting a reason is already supported by the REST API.

```
state_reason string or null

The reason for the state change. Ignored unless state is changed.

Can be one of: completed, not_planned, reopened, null 
```

https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue
