### ISSUE TITLE
Loop while Unlocking an Issue 

### ISSUE THREAD

**Issue by nitheesh-daram** [dessant/label-actions#23]
While Unlocking an issue with adding a label goes in a loop

`unlocks -> locks again -> unlocks `

my yml files look like this 

`lock-unlock.yml` under `.github/workflows/`
```
name: 'lock/unlock issues'

on:
  issues:
    types: labeled

permissions:
  issues: write


jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v3
        with:
          process-only : 'issues'
          config-path : '.github/lock-unlock.yml'
```

`lock-unlock.yml` under `.github/`

``` 
'🚦 status: awaiting triage':
  issues:
      comment: >
          some random
      lock : true

'🏁 status: ready for dev':
  issues:
      comment: >
            The thread has been temporarily unlocked.Please follow our community guidelines.
      unlock : true
```

##ScreenShots
![image](https://github.com/EddieHubCommunity/LinkFree/assets/54185106/da931020-ec82-411e-9d1f-f6127b1168e7)

**Comment by nitheesh-daram** [comment]
This seems to happen only when you have a comment while unlocking 
![image](https://github.com/dessant/label-actions/assets/54185106/22c30e6a-8062-407a-8d9b-12d4d33fd92b)

**Comment by dessant** [comment]
The thread must be unlocked to post a comment, and because the action performs these tasks without taking into account the next step, we get this unnecessary unlocking and locking. We are going to check if there is any locking instruction in the list of tasks when making a comment to avoid this issue.
