### ISSUE TITLE
Feature request: It will be great to fire a github actions

### ISSUE THREAD

**Issue by gugaiz** [dessant/label-actions#5]
I think it will be great feature to fire a github action based on labels.

Thanks!

**Comment by dessant** [comment]
Hi! I'm not aware of GitHub Apps being able to launch actions, they are typically triggered by events declared in the workflow.

Here are the docs for running an action when an issue is labeled: https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#issues-event-issues

I don't immediately see how to filter by the label name, but it should be possible.
