### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by NargiT** [dessant/label-actions#6]
Hello,

Would be nice to have a docker image so I can try it directly in my k8s cluster.

**Comment by dessant** [comment]
This image should work, though I have not tested with k8s:

```dockerfile
FROM node:12.18.4-alpine3.11

ENV APP_VERSION v1.0.1

WORKDIR /web/app

RUN set -ex \
    && apk add --no-cache curl \
    && curl -fsSL https://github.com/dessant/label-actions/archive/$APP_VERSION.tar.gz -o app.tar.gz \
    && tar -xf app.tar.gz --strip-components=1 && rm app.tar.gz \
    && yarn install --ignore-engines --production \
    && apk del curl

EXPOSE 3000

CMD ["yarn", "start"]
```

**Comment by NargiT** [comment]
thx I was more hoping for an image available on the docker hub :), beeing behind a company proxy our build tool does not have access to internet. so using curl for github will not work. where as docker pull will work thanks to internal mirrors.

any way thanks I will have a look and try

**Comment by dessant** [comment]
I plan to port this app to GitHub actions in the next month, so there will be no need to fiddle with self-hosting. I'll update you here when the action is ready.

**Comment by dessant** [comment]
The project has been ported to GitHub actions, you can find the documentation in the README: https://github.com/dessant/label-actions#readme

Let me know if you need any help with setting up the action.
