### ISSUE TITLE
Support for add/remove labels

### ISSUE THREAD

**Issue by AlexSkorkin** [dessant/label-actions#7]
In addition to the close/lock/open actions, it would be nice to have add/remove additional labels actions when an issue/pr is labeled/unlabeled.

Would you accept a PR for this?

**Comment by dessant** [comment]
Hi Alex! The app will be ported to GitHub actions in the next two weeks, and I could add the feature there. I'll let you know when the new action is ready.

**Comment by AlexSkorkin** [comment]
Hi, sounds awesome. Thank a lot for your work!

**Comment by AlexSkorkin** [comment]
Hi @dessant,
My apologizes for disturbing you. Have you started to port the app to GitHub actions?

**Comment by dessant** [comment]
Hi Alex, I have a local port that needs a bit more cleanup and docs, you should expect a release in the next 2 days.

**Comment by dessant** [comment]
The project has been ported to GitHub actions, you can find the documentation in the README: https://github.com/dessant/label-actions#readme

Let me know if you need any help with setting up the action.
