### ISSUE TITLE
Feature suggestion: Support commenting on discussion when labeled

### ISSUE THREAD

**Issue by HonkingGoose** [dessant/label-actions#8]
## Feature suggestion

Support commenting on labeled discussions.
GitHub now allows maintainers to add label(s) to a discussion in the same way as an issue.

The action currently only supports `issue` or `pull request` types.

It would be very nice if the action can comment on `discussion` type as well.

## Why this would be nice to have?

As a triagist on the `renovatebot/renovate` repository I frequently apply certain labels to let contributors know we need something from them, either formatting logs properly, making a minimal reproduction etc.
We now frequently convert a issue to a discussion, but sometimes we still need something from the contributor in the discussion.

It would be very very nice if we could use the labels on discussions the same way as on issues. This way the maintainers can use the standard templates, instead of typing out a response manually every time.

## Are you willing to work on this?

I cannot offer help making this feature. If this is too much work, or outside the scope of what you want the action to do, feel free to close the issue. 😉

**Comment by dessant** [comment]
Hi @HonkingGoose, I'd like to have this feature. It looks like the necessary events are there, but there's no REST API support so far, though it may be doable with the GraphQL API.

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#discussion
https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions

**Comment by HonkingGoose** [comment]
Thank you for responding to me! 😄 I'm happy that you want to have this feature as well. I'm sorry that I cannot offer help to build the feature.

**Comment by dessant** [comment]
Discussions are now supported in version 2.2.0, let me know if you need help with configuring the action.

**Comment by HonkingGoose** [comment]
Oh wow! Thank you very much for making this feature! 😄 ❤️ 

I'll go configure it, and will ping you if I get stuck.
